language: php
dist: trusty
group: edge

php:
  - 7.2
  - 7.3
  - 7.4

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - composer require --dev phpstan/phpstan
  - composer dump-autoload -o

script:
  - ./bin/phpstan analyse src/ --level=max
  - ./bin/phpspec run
  - ./bin/php-coveralls -v --exclude-no-stmt

notifications:
  email: false

matrix:
  fast_finish: true
