language: php

php:
  - 5.6
  - 7
  - 7.1

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
  - ./bin/phpspec run
  - ./bin/coveralls -v --exclude-no-stmt

notifications:
  email: false

matrix:
  fast_finish: true
