language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer config -g github-oauth.github.com $GITHUB_COMPOSER_AUTH
  - composer self-update
  - composer install --prefer-dist --no-interaction
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then composer global require --dev phpstan/phpstan; fi
  - composer dump-autoload -o

script:
  - if [[ $TRAVIS_PHP_VERSION = 7.1 ]]; then ~/.composer/vendor/bin/phpstan analyse src/ --level=7; fi
  - ./bin/phpspec run
  - ./bin/coveralls -v --exclude-no-stmt

notifications:
  email: false

matrix:
  fast_finish: true
